# Generated by Django 3.0.8 on 2021-01-14 13:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customstaff', '0002_auto_20210114_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incrementall',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 1, 14, 13, 58, 2, 170874, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2021, 1, 14, 13, 58, 2, 165456, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='endtime',
            field=models.TimeField(default=datetime.datetime(2021, 1, 14, 13, 58, 2, 165474, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2021, 1, 14, 13, 58, 2, 165413, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='starttime',
            field=models.TimeField(default=datetime.datetime(2021, 1, 14, 13, 58, 2, 165435, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2021, 1, 14, 13, 58, 2, 159398, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='nonteachingstaffdetail',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='nonteachingstaffdetail',
            name='supervisor',
            field=models.ManyToManyField(blank=True, null=True, related_name='supervisor', to='customstaff.Supervisor'),
        ),
        migrations.AlterField(
            model_name='secretarydetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2021, 1, 14, 13, 58, 2, 161467, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supervisordetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2021, 1, 14, 13, 58, 2, 162195, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingstaffdetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2021, 1, 14, 13, 58, 2, 158510, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='viceprincipaldetail',
            name='firstday',
            field=models.DateField(default=datetime.datetime(2021, 1, 14, 13, 58, 2, 163618, tzinfo=utc)),
        ),
    ]
