# Generated by Django 3.0.8 on 2020-08-04 10:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(default='input', max_length=50)),
                ('description', models.TextField(blank=True, default='testing')),
                ('date', models.DateField(default=datetime.datetime(2020, 8, 4, 10, 43, 36, 446115, tzinfo=utc))),
                ('email', models.EmailField(default='default@test.edu', max_length=254)),
            ],
        ),
    ]
