# Generated by Django 3.0.8 on 2020-08-06 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0002_auto_20200804_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 6, 13, 40, 17, 126076, tzinfo=utc)),
        ),
    ]
