# Generated by Django 3.0.8 on 2020-08-08 05:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0003_auto_20200806_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 8, 5, 11, 18, 117517, tzinfo=utc)),
        ),
    ]
