# Generated by Django 3.0.8 on 2020-08-08 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0006_auto_20200808_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 8, 12, 31, 15, 646784, tzinfo=utc)),
        ),
    ]
