# Generated by Django 3.0.8 on 2020-08-08 12:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0008_auto_20200808_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 8, 12, 50, 26, 377667, tzinfo=utc)),
        ),
    ]
