# Generated by Django 3.0.8 on 2020-08-09 06:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0009_auto_20200808_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 9, 6, 55, 21, 618223, tzinfo=utc)),
        ),
    ]
