# Generated by Django 3.0.8 on 2020-08-09 08:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0015_auto_20200809_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 9, 8, 36, 11, 704119, tzinfo=utc)),
        ),
    ]
