# Generated by Django 3.0.8 on 2020-08-10 08:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0017_auto_20200809_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 10, 8, 26, 49, 664064, tzinfo=utc)),
        ),
    ]
