# Generated by Django 3.0.8 on 2020-08-10 09:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0019_auto_20200810_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 10, 9, 41, 33, 846841, tzinfo=utc)),
        ),
    ]
