# Generated by Django 3.0.8 on 2020-08-10 10:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0022_auto_20200810_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 10, 10, 0, 56, 970610, tzinfo=utc)),
        ),
    ]
