# Generated by Django 3.0.8 on 2020-08-10 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0026_auto_20200810_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 10, 10, 32, 2, 250464, tzinfo=utc)),
        ),
    ]
