# Generated by Django 3.0.8 on 2020-08-10 15:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0035_auto_20200810_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 10, 15, 8, 31, 200410, tzinfo=utc)),
        ),
    ]
