# Generated by Django 3.0.8 on 2020-08-11 08:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0042_auto_20200811_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 11, 8, 7, 27, 678102, tzinfo=utc)),
        ),
    ]
