# Generated by Django 3.0.8 on 2020-08-11 09:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0049_auto_20200811_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 11, 9, 2, 36, 365597, tzinfo=utc)),
        ),
    ]
