# Generated by Django 3.0.8 on 2020-08-12 12:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0055_auto_20200812_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 12, 12, 1, 24, 796852, tzinfo=utc)),
        ),
    ]
