# Generated by Django 3.0.8 on 2020-08-13 09:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0057_auto_20200812_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 13, 9, 33, 18, 126333, tzinfo=utc)),
        ),
    ]
