# Generated by Django 3.0.8 on 2020-08-13 09:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0058_auto_20200813_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 13, 9, 37, 41, 897068, tzinfo=utc)),
        ),
    ]
