# Generated by Django 3.0.8 on 2020-08-14 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0062_auto_20200813_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 14, 8, 23, 14, 290570, tzinfo=utc)),
        ),
    ]
