# Generated by Django 3.0.8 on 2020-08-14 09:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0066_auto_20200814_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 14, 9, 38, 36, 932275, tzinfo=utc)),
        ),
    ]
