# Generated by Django 3.0.8 on 2020-08-15 10:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0068_auto_20200815_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 15, 10, 26, 48, 197912, tzinfo=utc)),
        ),
    ]
