# Generated by Django 3.0.8 on 2020-08-15 10:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0071_auto_20200815_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 15, 10, 38, 49, 525372, tzinfo=utc)),
        ),
    ]
