# Generated by Django 3.0.8 on 2020-08-15 10:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0072_auto_20200815_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 15, 10, 50, 12, 361225, tzinfo=utc)),
        ),
    ]
