# Generated by Django 3.0.8 on 2020-08-17 06:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0075_auto_20200816_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 17, 6, 41, 45, 100607, tzinfo=utc)),
        ),
    ]
