# Generated by Django 3.0.8 on 2020-08-17 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0077_auto_20200817_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 17, 7, 5, 22, 883529, tzinfo=utc)),
        ),
    ]
