# Generated by Django 3.0.8 on 2020-08-17 08:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0079_auto_20200817_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 17, 8, 15, 15, 492502, tzinfo=utc)),
        ),
    ]
