# Generated by Django 3.0.8 on 2020-08-17 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0080_auto_20200817_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 17, 8, 19, 17, 964642, tzinfo=utc)),
        ),
    ]
