# Generated by Django 3.0.8 on 2020-08-17 09:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0084_auto_20200817_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 17, 9, 30, 20, 818944, tzinfo=utc)),
        ),
    ]
