# Generated by Django 3.0.8 on 2020-08-17 09:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0085_auto_20200817_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 17, 9, 38, 0, 836530, tzinfo=utc)),
        ),
    ]
