# Generated by Django 3.0.8 on 2020-08-18 10:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0089_auto_20200817_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 18, 10, 18, 6, 816477, tzinfo=utc)),
        ),
    ]
