# Generated by Django 3.0.8 on 2020-08-24 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0092_auto_20200824_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 24, 13, 51, 41, 854411, tzinfo=utc)),
        ),
    ]
