# Generated by Django 3.0.8 on 2020-08-24 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0093_auto_20200824_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 24, 14, 10, 10, 636669, tzinfo=utc)),
        ),
    ]
