# Generated by Django 3.0.8 on 2020-08-25 03:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0097_auto_20200824_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 25, 3, 52, 40, 661957, tzinfo=utc)),
        ),
    ]
