# Generated by Django 3.0.8 on 2020-08-25 14:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0098_auto_20200825_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 25, 14, 12, 54, 89473, tzinfo=utc)),
        ),
    ]
