# Generated by Django 3.0.8 on 2020-08-26 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0102_auto_20200826_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 26, 9, 6, 3, 790627, tzinfo=utc)),
        ),
    ]
