# Generated by Django 3.0.8 on 2020-08-28 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0103_auto_20200826_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 8, 23, 52, 386951, tzinfo=utc)),
        ),
    ]
