# Generated by Django 3.0.8 on 2020-08-28 11:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0104_auto_20200828_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 11, 0, 13, 151177, tzinfo=utc)),
        ),
    ]
