# Generated by Django 3.0.8 on 2020-08-29 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0105_auto_20200828_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 29, 14, 14, 27, 536305, tzinfo=utc)),
        ),
    ]
