# Generated by Django 3.0.8 on 2020-08-30 08:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0106_auto_20200829_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 30, 8, 20, 23, 966776, tzinfo=utc)),
        ),
    ]
