# Generated by Django 3.0.8 on 2020-08-30 08:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0108_auto_20200830_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 30, 8, 29, 17, 159678, tzinfo=utc)),
        ),
    ]
