# Generated by Django 3.0.8 on 2020-08-30 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0109_auto_20200830_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 30, 8, 31, 22, 910150, tzinfo=utc)),
        ),
    ]
