# Generated by Django 3.0.8 on 2020-09-01 08:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0111_auto_20200830_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 1, 8, 55, 5, 73408, tzinfo=utc)),
        ),
    ]
