# Generated by Django 3.0.8 on 2020-09-07 09:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0114_auto_20200901_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 7, 9, 56, 24, 549909, tzinfo=utc)),
        ),
    ]
