# Generated by Django 3.0.8 on 2020-09-07 10:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0117_auto_20200907_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 7, 10, 37, 23, 254631, tzinfo=utc)),
        ),
    ]
