# Generated by Django 3.0.8 on 2020-09-09 13:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0122_auto_20200909_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 9, 13, 25, 59, 729685, tzinfo=utc)),
        ),
    ]
