# Generated by Django 3.0.8 on 2020-09-10 03:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0124_auto_20200909_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 10, 3, 18, 33, 429263, tzinfo=utc)),
        ),
    ]
