# Generated by Django 3.0.8 on 2020-09-10 04:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0125_auto_20200910_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 10, 4, 16, 3, 254636, tzinfo=utc)),
        ),
    ]
