# Generated by Django 3.0.8 on 2020-09-21 11:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0127_auto_20200910_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 21, 11, 18, 43, 807680, tzinfo=utc)),
        ),
    ]
