# Generated by Django 3.0.8 on 2020-10-04 12:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0129_auto_20200928_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 4, 12, 26, 7, 398278, tzinfo=utc)),
        ),
    ]
