# Generated by Django 3.0.8 on 2020-10-07 02:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0130_auto_20201004_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 7, 2, 11, 22, 598894, tzinfo=utc)),
        ),
    ]
