# Generated by Django 3.0.8 on 2020-10-07 02:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0131_auto_20201007_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 7, 2, 57, 33, 255653, tzinfo=utc)),
        ),
    ]
