# Generated by Django 3.0.8 on 2020-10-07 03:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0132_auto_20201007_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 7, 3, 54, 28, 619088, tzinfo=utc)),
        ),
    ]
