# Generated by Django 3.0.8 on 2020-10-07 04:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0133_auto_20201007_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 7, 4, 34, 31, 52191, tzinfo=utc)),
        ),
    ]
