# Generated by Django 3.0.8 on 2020-10-08 02:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0135_auto_20201007_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 2, 26, 49, 652341, tzinfo=utc)),
        ),
    ]
