# Generated by Django 3.0.8 on 2020-10-08 08:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0137_auto_20201008_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 8, 5, 15, 358092, tzinfo=utc)),
        ),
    ]
