# Generated by Django 3.0.8 on 2020-10-08 08:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0138_auto_20201008_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 8, 8, 59, 12, 65905, tzinfo=utc)),
        ),
    ]
