# Generated by Django 3.0.8 on 2020-10-17 09:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0143_auto_20201017_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 17, 9, 0, 18, 455047, tzinfo=utc)),
        ),
    ]
