# Generated by Django 3.0.8 on 2020-10-19 08:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0144_auto_20201017_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 19, 8, 55, 28, 446597, tzinfo=utc)),
        ),
    ]
