# Generated by Django 3.0.8 on 2020-10-19 08:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0145_auto_20201019_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 19, 8, 57, 31, 353752, tzinfo=utc)),
        ),
    ]
