# Generated by Django 3.0.8 on 2020-10-20 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0147_auto_20201020_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 20, 8, 31, 24, 536324, tzinfo=utc)),
        ),
    ]
