# Generated by Django 3.0.8 on 2020-10-22 01:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0149_auto_20201022_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 22, 1, 46, 50, 817242, tzinfo=utc)),
        ),
    ]
