# Generated by Django 3.0.8 on 2020-10-28 08:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0157_auto_20201028_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 28, 8, 24, 43, 584910, tzinfo=utc)),
        ),
    ]
