# Generated by Django 3.0.8 on 2020-10-30 15:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0158_auto_20201028_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 30, 15, 3, 41, 833828, tzinfo=utc)),
        ),
    ]
