# Generated by Django 3.0.8 on 2020-11-03 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0159_auto_20201030_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 9, 25, 9, 125590, tzinfo=utc)),
        ),
    ]
