# Generated by Django 3.0.8 on 2020-11-03 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0160_auto_20201103_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 9, 57, 32, 817879, tzinfo=utc)),
        ),
    ]
