# Generated by Django 3.0.8 on 2020-11-04 00:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0161_auto_20201103_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 4, 0, 32, 3, 374531, tzinfo=utc)),
        ),
    ]
