# Generated by Django 3.0.8 on 2020-11-08 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0164_auto_20201108_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 10, 30, 13, 141332, tzinfo=utc)),
        ),
    ]
