# Generated by Django 3.0.8 on 2020-11-18 01:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0165_auto_20201108_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 18, 1, 55, 29, 367805, tzinfo=utc)),
        ),
    ]
