# Generated by Django 3.0.8 on 2020-11-18 01:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0166_auto_20201118_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 18, 1, 56, 32, 446276, tzinfo=utc)),
        ),
    ]
