# Generated by Django 3.0.8 on 2020-11-18 02:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0170_auto_20201118_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 18, 2, 3, 19, 627705, tzinfo=utc)),
        ),
    ]
