# Generated by Django 3.0.8 on 2020-11-19 06:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0171_auto_20201118_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 19, 6, 5, 33, 21130, tzinfo=utc)),
        ),
    ]
