# Generated by Django 3.0.8 on 2020-11-20 00:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0172_auto_20201119_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 20, 0, 19, 45, 921119, tzinfo=utc)),
        ),
    ]
