# Generated by Django 3.0.8 on 2020-12-01 10:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0173_auto_20201120_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 1, 10, 2, 30, 467751, tzinfo=utc)),
        ),
    ]
