# Generated by Django 3.0.8 on 2020-12-30 08:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0174_auto_20201201_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 30, 8, 2, 18, 835770, tzinfo=utc)),
        ),
    ]
