# Generated by Django 3.0.8 on 2020-12-30 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0175_auto_20201230_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 30, 8, 4, 42, 320980, tzinfo=utc)),
        ),
    ]
