# Generated by Django 3.0.8 on 2020-12-30 09:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0180_auto_20201230_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 30, 9, 37, 41, 422925, tzinfo=utc)),
        ),
    ]
