# Generated by Django 3.0.8 on 2021-01-14 05:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0181_auto_20201230_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 14, 5, 52, 52, 793894, tzinfo=utc)),
        ),
    ]
