# Generated by Django 3.0.8 on 2021-01-17 08:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0191_auto_20210114_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 17, 8, 13, 53, 861852, tzinfo=utc)),
        ),
    ]
