# Generated by Django 3.0.8 on 2021-01-17 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0192_auto_20210117_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 17, 9, 4, 16, 981952, tzinfo=utc)),
        ),
    ]
