# Generated by Django 3.0.8 on 2021-02-09 08:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0193_auto_20210117_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 9, 8, 42, 11, 208971, tzinfo=utc)),
        ),
    ]
