# Generated by Django 3.0.8 on 2021-02-10 12:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0197_auto_20210210_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 10, 12, 46, 29, 765493, tzinfo=utc)),
        ),
    ]
