# Generated by Django 3.0.8 on 2021-02-21 06:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0199_auto_20210210_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 21, 6, 56, 35, 279467, tzinfo=utc)),
        ),
    ]
