# Generated by Django 3.0.8 on 2021-03-01 04:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0201_auto_20210221_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 1, 4, 30, 9, 246432, tzinfo=utc)),
        ),
    ]
