# Generated by Django 3.0.8 on 2021-03-01 08:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0202_auto_20210301_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 1, 8, 6, 35, 582534, tzinfo=utc)),
        ),
    ]
