# Generated by Django 3.0.8 on 2021-03-07 12:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0203_auto_20210301_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 7, 12, 40, 43, 533439, tzinfo=utc)),
        ),
    ]
