# Generated by Django 3.0.8 on 2021-03-08 02:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Timeoff', '0204_auto_20210307_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 8, 2, 11, 32, 300516, tzinfo=utc)),
        ),
    ]
